### ISSUE TITLE
关于我遇到的几个问题。

### ISSUE THREAD

**Issue by yuhanle** [SergioChan/SCTableViewCell#1]
当然这还是原型，但还是希望您能看到我所遇到的几个小问题。

1、Cell的滑动，当前会影响tableView的上下滑动。这个主要是手势冲突

2、可以同时滑动多个Cell，这样是不合理的。   我的解决办法是在编辑模式，table上加一层透明的view，点击会恢复正常模式

这是通俗的两个小问题

**Comment by SergioChan** [comment]
恩。。感谢您指出这些问题~
第一个问题好像邮箱做的也是cell滑动也就是进入编辑状态之后，如果touch没有结束，tableview就不能滑动。。如果tableview能滑动的话，用户也很难控制自己右滑到底删除这个操作吧。微信和QQ的滑动删除貌似也是不会在y轴上有位移。。
第二个问题我会尽快解决的~确实不能同时编辑多个cell。。

感谢~

**Comment by xxycode** [comment]
滑动的时候应该重置cell，而且编辑状态的应该只有一个

**Comment by SergioChan** [comment]
@xxycode 你仔细注意的话邮箱和大部分滑动菜单不一样。。用系统tableviewAction实现菜单出现之后再次滑动正常的话会重置cell，但是邮箱的效果是你可以从当前位置继续开始滑。。如果是点击才重置cell，编辑状态确实只能有一个
